version: 2.1
jobs:
  build:
    docker:
      - image: debian:latest # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: echo "hello world" # run the `echo` command
      - run:
          name: basic info
          command: |
            whoami
            pwd

      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get -y install python3 python3-pip tesseract-ocr
            pip3 install -r requirements.txt


      - run:
          name: run app
          command: |
            cd src && python3 service.py



